import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import com.sun.tools.attach.VirtualMachine;
import com.sun.tools.attach.VirtualMachineDescriptor;
import javax.management.MBeanServerConnection;
import javax.management.JMX;
import javax.management.ObjectName;
import javax.management.remote.JMXConnector;
import javax.management.remote.JMXConnectorFactory;
import javax.management.remote.JMXServiceURL;
import java.io.*;
import java.lang.management.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import jdk.management.jfr.FlightRecorderMXBean;
import jdk.management.jfr.RecordingInfo;
import jdk.jfr.consumer.RecordedEvent;
import jdk.jfr.consumer.RecordedFrame;
import jdk.jfr.consumer.RecordingFile;

public final class JvmPulseServer {
 private static final Path PUBLIC=Path.of("public").toAbsolutePath().normalize();
 private static final Path CAPTURES=Path.of("captures").toAbsolutePath().normalize();
 private static final String SELF=Long.toString(ProcessHandle.current().pid());
 private static final Map<String,Target> TARGETS=new ConcurrentHashMap<>();
 public static void main(String[] args)throws Exception{
  int port=args.length>0?Integer.parseInt(args[0]):8080;TARGETS.put(SELF,Target.local());
  HttpServer server=HttpServer.create(new InetSocketAddress("127.0.0.1",port),0);
  Files.createDirectories(CAPTURES);server.createContext("/api/apps",JvmPulseServer::apps);server.createContext("/api/metrics",JvmPulseServer::metrics);server.createContext("/api/config",JvmPulseServer::config);server.createContext("/api/threads",JvmPulseServer::threads);server.createContext("/api/histogram",JvmPulseServer::histogram);server.createContext("/api/heap",JvmPulseServer::heap);server.createContext("/api/jfr",JvmPulseServer::jfr);server.createContext("/",JvmPulseServer::staticFile);
  server.setExecutor(Executors.newVirtualThreadPerTaskExecutor());server.start();System.out.printf("JVM Pulse running at http://localhost:%d (PID %s)%n",port,SELF);
 }
 private static void apps(HttpExchange x)throws IOException{
  if(!get(x))return;List<VirtualMachineDescriptor> vms=VirtualMachine.list();Set<String> live=new HashSet<>();StringJoiner json=new StringJoiner(",","[","]");
  for(VirtualMachineDescriptor vm:vms){live.add(vm.id());String name=vm.displayName().isBlank()?"Java process":vm.displayName();if(vm.id().equals(SELF))name="JVM Pulse (this monitor)";json.add("{\"pid\":\""+esc(vm.id())+"\",\"name\":\""+esc(name)+"\",\"self\":"+vm.id().equals(SELF)+"}");}
  TARGETS.entrySet().removeIf(e->!e.getKey().equals(SELF)&&!live.contains(e.getKey())&&close(e.getValue()));send(x,200,"application/json",json.toString());
 }
 private static void metrics(HttpExchange x)throws IOException{
  if(!get(x))return;String pid=query(x,"pid").orElse(SELF);
  try{Target target=TARGETS.computeIfAbsent(pid,key->{try{return Target.attach(key);}catch(Exception e){throw new AttachFailure(e);}});send(x,200,"application/json",target.metrics(pid));}
  catch(Exception e){Target target=TARGETS.remove(pid);if(target!=null&&!pid.equals(SELF))target.close();send(x,502,"application/json","{\"error\":\"Unable to monitor PID "+esc(pid)+": "+esc(root(e))+"\"}");}
 }
 private static void config(HttpExchange x)throws IOException{
  if(!get(x))return;String pid=query(x,"pid").orElse(SELF);
  try{Target target=TARGETS.computeIfAbsent(pid,key->{try{return Target.attach(key);}catch(Exception e){throw new AttachFailure(e);}});send(x,200,"application/json",target.config(pid));}
  catch(Exception e){send(x,502,"application/json","{\"error\":\"Unable to read configuration for PID "+esc(pid)+": "+esc(root(e))+"\"}");}
 }
 private static void threads(HttpExchange x)throws IOException{diagnosticJson(x,"threads");}
 private static void histogram(HttpExchange x)throws IOException{diagnosticJson(x,"histogram");}
 private static void heap(HttpExchange x)throws IOException{
  if(!get(x))return;String pid=query(x,"pid").orElse(SELF);
  try{send(x,200,"application/json",target(pid).heapAnalysis(pid));}catch(Exception e){send(x,502,"application/json","{\"error\":\"Heap analysis failed: "+esc(root(e))+"\"}");}
 }
 private static void diagnosticJson(HttpExchange x,String operation)throws IOException{
  if(!get(x))return;String pid=query(x,"pid").orElse(SELF);
  try{Target target=target(pid);String body=operation.equals("threads")?target.threadSnapshot():target.histogram();send(x,200,"application/json",body);}
  catch(Exception e){send(x,502,"application/json","{\"error\":\"Diagnostic failed: "+esc(root(e))+"\"}");}
 }
 private static void jfr(HttpExchange x)throws IOException{
  if(!get(x))return;String pid=query(x,"pid").orElse(SELF),action=query(x,"action").orElse("status");
  try{Target target=target(pid);if(action.equals("start")){int seconds=Math.max(10,Math.min(300,Integer.parseInt(query(x,"duration").orElse("30"))));send(x,200,"application/json",target.startRecording(seconds));return;}if(action.equals("download")){long id=Long.parseLong(query(x,"id").orElseThrow());byte[] data=target.recording(id);x.getResponseHeaders().set("Content-Type","application/octet-stream");x.getResponseHeaders().set("Content-Disposition","attachment; filename=jvm-pulse-"+pid+"-"+id+".jfr");x.sendResponseHeaders(200,data.length);try(OutputStream out=x.getResponseBody()){out.write(data);}return;}if(action.equals("analyze")){long id=Long.parseLong(query(x,"id").orElseThrow());send(x,200,"application/json",target.analyzeRecording(id));return;}send(x,200,"application/json",target.recordings());}
  catch(Exception e){send(x,502,"application/json","{\"error\":\"JFR operation failed: "+esc(root(e))+"\"}");}
 }
 private static Target target(String pid)throws Exception{return TARGETS.computeIfAbsent(pid,key->{try{return Target.attach(key);}catch(Exception e){throw new AttachFailure(e);}});}
 private static final class Target implements AutoCloseable{
  final MBeanServerConnection connection;final JMXConnector connector;final MemoryMXBean memory;final ThreadMXBean threads;final ClassLoadingMXBean classes;final RuntimeMXBean runtime;final com.sun.management.OperatingSystemMXBean os;final com.sun.management.HotSpotDiagnosticMXBean hotSpot;final FlightRecorderMXBean flightRecorder;final List<GarbageCollectorMXBean> gc=new ArrayList<>();final Map<Long,Long> previousThreadCpu=new HashMap<>();long previousCpuTime=-1,previousSampleNanos=-1,previousThreadSampleNanos=-1;
  Target(MBeanServerConnection c,JMXConnector connector)throws Exception{this.connection=c;this.connector=connector;memory=proxy(c,ManagementFactory.MEMORY_MXBEAN_NAME,MemoryMXBean.class);threads=proxy(c,ManagementFactory.THREAD_MXBEAN_NAME,ThreadMXBean.class);classes=proxy(c,ManagementFactory.CLASS_LOADING_MXBEAN_NAME,ClassLoadingMXBean.class);runtime=proxy(c,ManagementFactory.RUNTIME_MXBEAN_NAME,RuntimeMXBean.class);os=proxy(c,ManagementFactory.OPERATING_SYSTEM_MXBEAN_NAME,com.sun.management.OperatingSystemMXBean.class);hotSpot=JMX.newMXBeanProxy(c,new ObjectName("com.sun.management:type=HotSpotDiagnostic"),com.sun.management.HotSpotDiagnosticMXBean.class);flightRecorder=JMX.newMXBeanProxy(c,new ObjectName("jdk.management.jfr:type=FlightRecorder"),FlightRecorderMXBean.class);for(ObjectName n:c.queryNames(new ObjectName("java.lang:type=GarbageCollector,name=*"),null))gc.add(proxy(c,n.toString(),GarbageCollectorMXBean.class));if(threads.isThreadCpuTimeSupported()&&!threads.isThreadCpuTimeEnabled())try{threads.setThreadCpuTimeEnabled(true);}catch(Exception ignored){}}
  static Target local()throws Exception{return new Target(ManagementFactory.getPlatformMBeanServer(),null);}
  static Target attach(String pid)throws Exception{VirtualMachine vm=VirtualMachine.attach(pid);String address;try{address=vm.startLocalManagementAgent();}finally{vm.detach();}JMXConnector jmx=JMXConnectorFactory.connect(new JMXServiceURL(address));try{return new Target(jmx.getMBeanServerConnection(),jmx);}catch(Exception e){jmx.close();throw e;}}
  synchronized String metrics(String pid){MemoryUsage h=memory.getHeapMemoryUsage(),n=memory.getNonHeapMemoryUsage();long gcc=gc.stream().mapToLong(g->Math.max(0,g.getCollectionCount())).sum(),gct=gc.stream().mapToLong(g->Math.max(0,g.getCollectionTime())).sum();double processCpu=sampleProcessCpu();return"{"+sf("pid",pid)+f("timestamp",Instant.now().toEpochMilli())+f("processCpu",processCpu)+f("systemCpu",sane(os.getCpuLoad())*100)+f("heapUsed",h.getUsed())+f("heapCommitted",h.getCommitted())+f("heapMax",h.getMax())+f("nonHeapUsed",n.getUsed())+f("nonHeapCommitted",n.getCommitted())+f("physicalUsed",os.getTotalMemorySize()-os.getFreeMemorySize())+f("physicalTotal",os.getTotalMemorySize())+f("threads",threads.getThreadCount())+f("peakThreads",threads.getPeakThreadCount())+f("classes",classes.getLoadedClassCount())+f("gcCount",gcc)+f("gcTime",gct)+f("uptime",runtime.getUptime())+"\"processors\":"+os.getAvailableProcessors()+"}";}
  double sampleProcessCpu(){long now=System.nanoTime(),cpuTime=os.getProcessCpuTime();double load=0;if(previousCpuTime>=0&&cpuTime>=previousCpuTime&&now>previousSampleNanos){long cpuDelta=cpuTime-previousCpuTime,wallDelta=now-previousSampleNanos;load=cpuDelta/(double)wallDelta/Math.max(1,os.getAvailableProcessors())*100;}previousCpuTime=cpuTime;previousSampleNanos=now;return Math.max(0,Math.min(100,load));}
  String config(String pid){MemoryUsage heap=memory.getHeapMemoryUsage();StringJoiner collectors=new StringJoiner(",","[","]");for(GarbageCollectorMXBean collector:gc)collectors.add("\""+esc(collector.getName())+"\"");return"{"+sf("pid",pid)+sf("runtimeName",runtime.getName())+sf("vmName",runtime.getVmName())+sf("vmVendor",runtime.getVmVendor())+sf("vmVersion",runtime.getVmVersion())+sf("specName",runtime.getSpecName())+sf("specVendor",runtime.getSpecVendor())+sf("specVersion",runtime.getSpecVersion())+f("startTime",runtime.getStartTime())+f("processors",os.getAvailableProcessors())+f("heapInitial",heap.getInit())+f("heapMax",heap.getMax())+"\"garbageCollectors\":"+collectors+",\"inputArguments\":"+strings(runtime.getInputArguments())+"}";}
  synchronized String threadSnapshot(){long now=System.nanoTime(),elapsed=previousThreadSampleNanos<0?0:now-previousThreadSampleNanos;long[] ids=threads.getAllThreadIds();ThreadInfo[] infos=threads.getThreadInfo(ids,12);List<String> rows=new ArrayList<>();for(int i=0;i<ids.length;i++){ThreadInfo info=infos[i];if(info==null)continue;long cpu=threads.isThreadCpuTimeSupported()?threads.getThreadCpuTime(ids[i]):-1,old=previousThreadCpu.getOrDefault(ids[i],cpu),delta=Math.max(0,cpu-old);double percent=elapsed>0?Math.min(100,delta/(double)elapsed*100):0;previousThreadCpu.put(ids[i],cpu);String top=info.getStackTrace().length==0?"":info.getStackTrace()[0].toString();rows.add("{\"id\":"+ids[i]+",\"name\":\""+esc(info.getThreadName())+"\",\"state\":\""+info.getThreadState()+"\",\"cpu\":"+String.format(Locale.ROOT,"%.2f",percent)+",\"topFrame\":\""+esc(top)+"\"}");}previousThreadSampleNanos=now;Set<Long> live=new HashSet<>();for(long id:ids)live.add(id);previousThreadCpu.keySet().retainAll(live);rows.sort((a,b)->Double.compare(cpuValue(b),cpuValue(a)));return"{\"threads\":["+String.join(",",rows.subList(0,Math.min(20,rows.size())))+"]}";}
  String histogram()throws Exception{return"{\"output\":\""+esc(classHistogramOutput())+"\"}";}
  String classHistogramOutput()throws Exception{return String.valueOf(connection.invoke(new ObjectName("com.sun.management:type=DiagnosticCommand"),"gcClassHistogram",new Object[]{new String[]{"-all"}},new String[]{String[].class.getName()}));}
  String startRecording(int seconds)throws Exception{long id=flightRecorder.newRecording();flightRecorder.setPredefinedConfiguration(id,"profile");flightRecorder.setRecordingOptions(id,Map.of("name","JVM Pulse diagnostics","disk","true","duration",seconds+" s","maxAge","1 h","maxSize","104857600"));flightRecorder.startRecording(id);return"{\"id\":"+id+",\"duration\":"+seconds+"}";}
  String recordings(){StringJoiner json=new StringJoiner(",","{\"recordings\":[","]}");for(RecordingInfo info:flightRecorder.getRecordings())json.add("{\"id\":"+info.getId()+",\"name\":\""+esc(info.getName())+"\",\"state\":\""+info.getState()+"\",\"size\":"+info.getSize()+"}");return json.toString();}
  byte[] recording(long id)throws Exception{RecordingInfo selected=flightRecorder.getRecordings().stream().filter(info->info.getId()==id).findFirst().orElseThrow(()->new IllegalArgumentException("Recording not found"));if(!selected.getState().equals("STOPPED"))throw new IllegalStateException("Recording is still "+selected.getState());long stream=flightRecorder.openStream(id,Map.of("blockSize","50000"));try(ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] block;while((block=flightRecorder.readStream(stream))!=null)out.write(block);return out.toByteArray();}finally{flightRecorder.closeStream(stream);}}
  synchronized String heapAnalysis(String pid)throws Exception{MemoryUsage usage=memory.getHeapMemoryUsage();long required=Math.max(usage.getUsed()*2,512L*1024*1024),free=Files.getFileStore(CAPTURES).getUsableSpace();if(free<required)throw new IOException("Insufficient disk space. Need approximately "+required+" bytes, available "+free);String capture="heap-"+pid+"-"+UUID.randomUUID();Path dump=CAPTURES.resolve(capture+".hprof"),sourceInfo=CAPTURES.resolve(capture+".classpath");Files.writeString(sourceInfo,runtime.getClassPath());try{try{dumpHeapSingleThreaded(dump);}catch(Exception dumpFailure){long partialSize=Files.exists(dump)?Files.size(dump):0;return heapHistogramFallback(partialSize,"Heap dump creation failed: "+root(dumpFailure));}Path mat=Path.of("tools","mat","mat","ParseHeapDump.bat").toAbsolutePath().normalize();if(Files.isRegularFile(mat))try{return analyzeHeapWithMat(mat,dump);}catch(Exception matFailure){return heapHistogramFallback(Files.size(dump),"Eclipse MAT failed: "+root(matFailure));}long analyzerMb=Math.max(1024,Math.min(8192,required/(1024*1024)));Path java=Path.of(System.getProperty("java.home"),"bin",System.getProperty("os.name").startsWith("Windows")?"java.exe":"java");Process process=new ProcessBuilder(java.toString(),"-Xmx"+analyzerMb+"m","-cp",System.getProperty("java.class.path"),"HeapAnalyzer",dump.toString(),sourceInfo.toString()).redirectErrorStream(true).start();try(var executor=Executors.newVirtualThreadPerTaskExecutor()){Future<byte[]> output=executor.submit(()->process.getInputStream().readAllBytes());boolean finished=process.waitFor(10,TimeUnit.MINUTES);if(!finished){process.destroyForcibly();process.waitFor(30,TimeUnit.SECONDS);throw new IOException("Heap analysis exceeded 10 minutes");}String result=new String(output.get(30,TimeUnit.SECONDS),StandardCharsets.UTF_8);if(process.exitValue()!=0)return heapHistogramFallback(Files.size(dump),result);return result;}}finally{deleteCaptureEventually(dump);deleteFileEventually(sourceInfo);deleteMatArtifactsEventually(dump);}}
  void dumpHeapSingleThreaded(Path dump)throws Exception{connection.invoke(new ObjectName("com.sun.management:type=DiagnosticCommand"),"gcHeapDump",new Object[]{new String[]{"-parallel=1",dump.toString()}},new String[]{String[].class.getName()});}
  String analyzeHeapWithMat(Path mat,Path dump)throws Exception{Process process=new ProcessBuilder("cmd.exe","/d","/c",mat.toString(),dump.toString(),"-command=dominator_tree","-format=csv","-unzip","org.eclipse.mat.api:query").redirectErrorStream(true).start();String output;try(var executor=Executors.newVirtualThreadPerTaskExecutor()){Future<byte[]> captured=executor.submit(()->process.getInputStream().readAllBytes());if(!process.waitFor(15,TimeUnit.MINUTES)){process.destroyForcibly();process.waitFor(30,TimeUnit.SECONDS);throw new IOException("Eclipse MAT analysis exceeded 15 minutes");}output=new String(captured.get(30,TimeUnit.SECONDS),StandardCharsets.UTF_8);}if(process.exitValue()!=0)throw new IOException(output.isBlank()?"Eclipse MAT exited with code "+process.exitValue():output);String stem=dump.getFileName().toString().replaceFirst("\\.hprof$","");Path csv=dump.getParent().resolve(stem+"_Query").resolve("pages").resolve("Query_Command2.csv");if(!Files.isRegularFile(csv))throw new IOException("Eclipse MAT did not create a dominator CSV report");StringJoiner rows=new StringJoiner(",","[","]");int count=0;for(String line:Files.readAllLines(csv,StandardCharsets.UTF_8)){String[] columns=line.split(",",5);if(columns.length<3||columns[0].equals("Class Name"))continue;try{String className=columns[0].replaceFirst("\\s+@\\s+0x[0-9a-fA-F]+\\s*$","").replaceFirst("^class\\s+","").trim();long shallow=Long.parseLong(columns[1].trim()),retained=Long.parseLong(columns[2].trim());rows.add("{\"className\":\""+esc(className)+"\",\"instanceId\":0,\"shallowSize\":"+shallow+",\"retainedSize\":"+retained+",\"gcRootPath\":[\"Use Eclipse MAT Path to GC Roots for this object\"],\"source\":"+nullable(findSource(className,0))+",\"hint\":\""+esc(memoryHint(className))+"\"}");if(++count==20)break;}catch(NumberFormatException ignored){}}if(count==0)throw new IOException("Eclipse MAT dominator report contained no object rows");return"{\"dumpSize\":"+Files.size(dump)+",\"retainedSizesAvailable\":true,\"analysisEngine\":\"Eclipse MAT 1.17\",\"warning\":\"Analyzed with Eclipse MAT 1.17. Retained sizes are available; use MAT Path to GC Roots for full reference paths.\",\"dominators\":"+rows+"}";}
  String heapHistogramFallback(long dumpSize,String parserError)throws Exception{StringJoiner rows=new StringJoiner(",","[","]");int count=0;for(String line:classHistogramOutput().split("\\R")){String[] columns=line.trim().split("\\s+",4);if(columns.length<4||!columns[0].endsWith(":"))continue;try{long instances=Long.parseLong(columns[1]),bytes=Long.parseLong(columns[2]);String className=columns[3].split("\\s+",2)[0];rows.add("{\"className\":\""+esc(className)+"\",\"instanceId\":0,\"instances\":"+instances+",\"shallowSize\":"+bytes+",\"retainedSize\":0,\"gcRootPath\":[\"Unavailable in class-histogram fallback\"],\"source\":"+nullable(findSource(className,0))+",\"hint\":\""+esc(memoryHint(className))+"\"}");if(++count==20)break;}catch(NumberFormatException ignored){}}if(count==0)throw new IOException(parserError.isBlank()?"Heap parser failed and no class histogram was available":parserError);return"{\"dumpSize\":"+dumpSize+",\"retainedSizesAvailable\":false,\"histogramFallback\":true,\"warning\":\"The heap parser does not support this dump layout. Showing the 20 largest live classes by total shallow bytes; retained sizes and GC-root paths are unavailable.\",\"dominators\":"+rows+"}";}
  void deleteCaptureEventually(Path dump){for(int attempt=0;attempt<6;attempt++){try{deleteCapture(dump);return;}catch(IOException e){if(attempt<5)try{Thread.sleep(250L*(attempt+1));}catch(InterruptedException interrupted){Thread.currentThread().interrupt();return;}}}}
  void deleteFileEventually(Path file){for(int attempt=0;attempt<6;attempt++){try{Files.deleteIfExists(file);return;}catch(IOException e){if(attempt<5)try{Thread.sleep(250L*(attempt+1));}catch(InterruptedException interrupted){Thread.currentThread().interrupt();return;}}}}
  void deleteMatArtifactsEventually(Path dump){String stem=dump.getFileName().toString().replaceFirst("\\.hprof$","");for(int attempt=0;attempt<6;attempt++){try{try(var paths=Files.walk(CAPTURES)){for(Path path:paths.filter(p->!p.equals(CAPTURES)&&p.getFileName().toString().startsWith(stem+".")||p.getFileName().toString().startsWith(stem+"_")).sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(path);}return;}catch(IOException e){if(attempt<5)try{Thread.sleep(250L*(attempt+1));}catch(InterruptedException interrupted){Thread.currentThread().interrupt();return;}}}}
  void deleteCapture(Path dump)throws IOException{if(!dump.normalize().startsWith(CAPTURES))throw new IOException("Invalid capture path");Path cache=Path.of(dump+".nbcache");if(Files.isDirectory(cache))try(var paths=Files.walk(cache)){for(Path path:paths.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(path);}Files.deleteIfExists(dump);}
  String analyzeRecording(long id)throws Exception{byte[] data=recording(id);Path file=Files.createTempFile(CAPTURES,"jfr-",".jfr");Files.write(file,data);Map<String,Sample> methods=new HashMap<>(),allocations=new HashMap<>();int totalSamples=0;try(RecordingFile recording=new RecordingFile(file)){while(recording.hasMoreEvents()){RecordedEvent event=recording.readEvent();String type=event.getEventType().getName();if((type.equals("jdk.ExecutionSample")||type.equals("jdk.NativeMethodSample"))&&event.getStackTrace()!=null&&!event.getStackTrace().getFrames().isEmpty()){List<RecordedFrame> frames=event.getStackTrace().getFrames();RecordedFrame frame=frames.stream().filter(RecordedFrame::isJavaFrame).findFirst().orElse(frames.get(0));String className=frame.getMethod().getType().getName(),method=className+"."+frame.getMethod().getName(),stack=stack(frames);Sample sample=methods.computeIfAbsent(method,key->new Sample(className,method,frame.getLineNumber(),stack));sample.value++;totalSamples++;}else if(type.startsWith("jdk.ObjectAllocation")&&event.hasField("objectClass")){String className=event.getClass("objectClass").getName();long bytes=event.hasField("weight")?event.getLong("weight"):event.hasField("allocationSize")?event.getLong("allocationSize"):event.hasField("tlabSize")?event.getLong("tlabSize"):0;Sample sample=allocations.computeIfAbsent(className,key->new Sample(className,className,0,""));sample.value+=Math.max(0,bytes);}}}finally{Files.deleteIfExists(file);}List<Sample> hot=methods.values().stream().sorted(Comparator.comparingLong((Sample s)->s.value).reversed()).limit(25).toList(),allocated=allocations.values().stream().sorted(Comparator.comparingLong((Sample s)->s.value).reversed()).limit(25).toList();StringJoiner hotJson=new StringJoiner(",","[","]"),allocationJson=new StringJoiner(",","[","]");for(Sample sample:hot){double percent=totalSamples==0?0:sample.value*100d/totalSamples;hotJson.add("{\"method\":\""+esc(sample.name)+"\",\"samples\":"+sample.value+",\"percent\":"+String.format(Locale.ROOT,"%.2f",percent)+",\"line\":"+sample.line+",\"stack\":\""+esc(sample.stack)+"\",\"source\":"+nullable(findSource(sample.className,sample.line))+",\"hint\":\""+esc(cpuHint(sample.name))+"\"}");}for(Sample sample:allocated)allocationJson.add("{\"className\":\""+esc(sample.className)+"\",\"bytes\":"+sample.value+",\"source\":"+nullable(findSource(sample.className,0))+",\"hint\":\""+esc(memoryHint(sample.className))+"\"}");return"{\"totalSamples\":"+totalSamples+",\"hotMethods\":"+hotJson+",\"allocations\":"+allocationJson+"}";}
  String stack(List<RecordedFrame> frames){StringJoiner text=new StringJoiner(" <- ");for(RecordedFrame frame:frames.subList(0,Math.min(8,frames.size()))){String name=frame.getMethod().getType().getName()+"."+frame.getMethod().getName();text.add(name+(frame.getLineNumber()>0?":"+frame.getLineNumber():""));}return text.toString();}
  String findSource(String className,int line){String outer=className.split("\\$",2)[0],relative=outer.replace('.','/')+".java";for(String entry:runtime.getClassPath().split(java.io.File.pathSeparator)){try{Path classes=Path.of(entry);if(classes.endsWith(Path.of("target","classes"))){Path source=classes.getParent().getParent().resolve("src/main/java").resolve(relative);if(Files.isRegularFile(source))return source.toString()+(line>0?":"+line:"");}}catch(Exception ignored){}}return null;}
  public void close(){if(connector!=null)try{connector.close();}catch(IOException ignored){}}
 }
 private static<T>T proxy(MBeanServerConnection c,String name,Class<T> type)throws IOException{return ManagementFactory.newPlatformMXBeanProxy(c,name,type);}
 private static boolean get(HttpExchange x)throws IOException{if("GET".equals(x.getRequestMethod()))return true;send(x,405,"text/plain","Method not allowed");return false;}
 private static Optional<String> query(HttpExchange x,String key){String q=x.getRequestURI().getRawQuery();if(q==null)return Optional.empty();return Arrays.stream(q.split("&")).map(v->v.split("=",2)).filter(v->v.length==2&&v[0].equals(key)).map(v->URLDecoder.decode(v[1],StandardCharsets.UTF_8)).findFirst();}
 private static boolean close(Target t){t.close();return true;}private static double sane(double v){return v<0||Double.isNaN(v)?0:v;}private static String f(String n,long v){return"\""+n+"\":"+v+",";}private static String f(String n,double v){return"\""+n+"\":"+String.format(Locale.ROOT,"%.2f",v)+",";}private static String sf(String n,String v){return"\""+n+"\":\""+esc(v)+"\",";}
 private static String strings(List<String> values){StringJoiner json=new StringJoiner(",","[","]");for(String value:values)json.add("\""+esc(value)+"\"");return json.toString();}
 private static double cpuValue(String json){int start=json.indexOf("\"cpu\":")+6,end=json.indexOf(',',start);return Double.parseDouble(json.substring(start,end));}
 private static String nullable(String value){return value==null?"null":"\""+esc(value)+"\"";}
 private static String cpuHint(String method){if(method.contains("java.util.regex"))return"Cache compiled patterns and avoid backtracking-heavy expressions.";if(method.contains("reflect")||method.contains("Method.invoke"))return"Reduce repeated reflective dispatch or cache resolved accessors.";if(method.contains("jackson")||method.contains("Json"))return"Review serialization volume, object mapping, and repeated mapper construction.";if(method.contains("log")||method.contains("Logger"))return"Avoid formatting high-volume log messages unless the level is enabled.";if(method.contains("HashMap")||method.contains("ConcurrentHashMap"))return"Inspect key distribution, resizing, and contention around shared maps.";return"Inspect this method's JFR call tree and optimize only the path exercised by the workload.";}
 private static String memoryHint(String className){if(className.equals("java.lang.String")||className.equals("byte[]")||className.equals("char[]"))return"Inspect payload duplication, cache keys, buffers, and string construction.";if(className.contains("HashMap")||className.contains("ConcurrentHashMap"))return"Review cache bounds, key lifecycle, and map ownership.";if(className.contains("ThreadLocal"))return"Ensure ThreadLocal values are removed when pooled-thread work completes.";if(className.startsWith("com.morningstar."))return"Compare retained instances across captures and inspect the shown GC-root ownership path.";return"Use retained size and the GC-root path to identify the owning component before changing allocation code.";}
 private static final class Sample{final String className,name,stack;final int line;long value;Sample(String className,String name,int line,String stack){this.className=className;this.name=name;this.line=line;this.stack=stack;}}
 private static String esc(String v){return v.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r").replace("\t","\\t");}private static String root(Throwable e){while(e.getCause()!=null)e=e.getCause();return Objects.toString(e.getMessage(),e.getClass().getSimpleName());}
 private static void staticFile(HttpExchange x)throws IOException{String request=x.getRequestURI().getPath();if(request.equals("/"))request="/index.html";Path file=PUBLIC.resolve(request.substring(1)).normalize();if(!file.startsWith(PUBLIC)||!Files.isRegularFile(file)){send(x,404,"text/plain","Not found");return;}String n=file.getFileName().toString(),type=n.endsWith(".css")?"text/css":n.endsWith(".js")?"application/javascript":"text/html";byte[] b=Files.readAllBytes(file);x.getResponseHeaders().set("Content-Type",type+"; charset=utf-8");x.sendResponseHeaders(200,b.length);try(OutputStream o=x.getResponseBody()){o.write(b);}}
 private static void send(HttpExchange x,int status,String type,String body)throws IOException{byte[] b=body.getBytes(StandardCharsets.UTF_8);x.getResponseHeaders().set("Content-Type",type+"; charset=utf-8");x.getResponseHeaders().set("Cache-Control","no-store");x.sendResponseHeaders(status,b.length);try(OutputStream o=x.getResponseBody()){o.write(b);}}
 private static final class AttachFailure extends RuntimeException{AttachFailure(Throwable e){super(e);}}
}
